# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(default='testModel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sale_acc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.SaleAccount'),
            preserve_default=False,
        ),
    ]
